### ISSUE TITLE
ImportError: cannot import name 'generate_detections'

### ISSUE THREAD

**Issue by RahulKej** [pruthvi03/DeepSortWithYolov3#1]
Tried using virtual environment to run the code, on Anaconda Navigator command prompt.

Issue faced on running "python object_tracker.py"

W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "object_tracker.py", line 27, in <module>
    from tools import generate_detections as gdet
ImportError: cannot import name 'generate_detections'

**Comment by pruthvi03** [comment]
@RahulKej I have added the tools folder and weights of my custom trained model in this repository. Now, you can run object_tracker.py.

**Comment by RahulKej** [comment]
Hello, thank you for your response.

Can you please check once if the repository has been updated, because I am unable to find the tools folder. Also, the weights folder contains only ignore.names file and the yolov3.tf weights are not present in it.

**Comment by pruthvi03** [comment]
Get weights and coco.names from this link: https://drive.google.com/drive/folders/1q8bBnO3RN1qhFHZRhVIdCVcGkHbBO4AH?usp=sharing
And now I have added the tools folder
